version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - database

  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swag_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

volumes:
  postgres_data:
