name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/backend/Dockerfile
        push: false
        tags: swag-todo-backend:latest
        load: true
        
    - name: Build frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: swag-todo-frontend:latest
        load: true
        
    - name: Create network
      run: docker network create swag-todo-network
      
    - name: Run database
      run: |
        docker run -d \
          --name swag-todo-db \
          --network swag-todo-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -e POSTGRES_DB=swag_todo \
          postgres:16-alpine
          
    - name: Run backend
      run: |
        docker run -d \
          --name swag-todo-backend \
          --network swag-todo-network \
          -e ASPNETCORE_ENVIRONMENT=Development \
          -e ASPNETCORE_URLS=http://+:8080 \
          -p 8080:8080 \
          swag-todo-backend:latest
          
    - name: Run frontend
      run: |
        docker run -d \
          --name swag-todo-frontend \
          --network swag-todo-network \
          -p 80:80 \
          swag-todo-frontend:latest
          
    - name: Wait for services to start
      run: sleep 15
      
    - name: Check if services are running
      run: |
        docker ps
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/hello || true
        curl -s -o /dev/null -w "%{http_code}" http://localhost:80 || true