name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-image:

    runs-on: ubuntu-latest

    outputs:
      date: ${{ steps.date.outputs.date }}

    steps:
      - uses: actions/checkout@v4
      - name: Get current date # get the date of the build
        id: date
      - name: Build the Docker image
        run: docker build . --file Dockerfile  --tag ghcr.io/replace-me-org/replace-me-image-name:${{ steps.date.outputs.date }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to the GitHub registry
        run: docker push ghcr.io/replace-me-org/replace-me-image-name:${{ steps.date.outputs.date }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: |
                    ssh-keyscan user@remote_server >> ~/.ssh/known_hosts    # Replace user@remote_server

      - name: Deploy to server
        run: |
          ssh user@remote_server << 'EOF'                         # Replace user@remote_server
            cd <REPLACE_ME_WITH_DOCKER_COMPOSE_FOLDER>            # Replace with your Docker Compose folder
            sed -i 's/^DOCKER_TAG=.*/DOCKER_TAG=${{ needs.build-push-image.outputs.date }}/' .env
            docker compose up -d
          EOF          
