name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/backend/Dockerfile
        push: false
        tags: swag-todo-backend:latest
        
    - name: Build frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: swag-todo-frontend:latest
